# Generated by Django 5.2.8 on 2025-11-20 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimiento', '0003_alter_mantenimiento_fallas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=11)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True)),
                ('contacto', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('coordenadas', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=9)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruta.ciudad')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruta.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('sedes', models.ManyToManyField(related_name='rutas', to='ruta.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometraje_inicio', models.IntegerField()),
                ('kilometraje_final', models.IntegerField()),
                ('estado', models.CharField(choices=[('programado', 'programado'), ('en curso', 'en curso'), ('completado', 'completado'), ('cancelado', 'cancelado')], max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('observaciones', models.TextField()),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruta.ruta')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Recojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField()),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruta.sede')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruta.viaje')),
            ],
        ),
    ]
