# Generated by Django 6.0 on 2026-04-03 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=9)),
            ],
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='contacto',
            new_name='persona',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombres',
            new_name='razon_social',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellidos',
        ),
        migrations.AddField(
            model_name='ciudad',
            name='distrito',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='departamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('celular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruta.celular')),
            ],
        ),
    ]
