# Generated by Django 6.0 on 2026-04-03 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0002_celular_rename_contacto_cliente_persona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruta.persona'),
        ),
    ]
