# Generated by Django 6.0 on 2026-04-03 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_rename_fecha_repostado_falla_fecha_reportado'),
        ('ruta', '0003_alter_cliente_persona'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruta.persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='celular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruta.celular'),
        ),
        migrations.AlterField(
            model_name='recojo',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruta.sede'),
        ),
        migrations.AlterField(
            model_name='recojo',
            name='viaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruta.viaje'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruta.ciudad'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruta.cliente'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='ruta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruta.ruta'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.vehiculo'),
        ),
    ]
