# Generated by Django 6.0 on 2026-04-03 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0004_alter_cliente_persona_alter_persona_celular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='contacto',
        ),
        migrations.AddField(
            model_name='sede',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruta.persona'),
        ),
    ]
