# Generated by Django 6.0 on 2026-04-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0005_remove_sede_contacto_sede_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='kilometraje_final',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
