# Generated by Django 6.0 on 2026-04-06 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0006_alter_viaje_kilometraje_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='celular',
        ),
        migrations.AddField(
            model_name='celular',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruta.persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruta.cliente'),
        ),
        migrations.AlterField(
            model_name='celular',
            name='numero',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
