# Generated by Django 6.0 on 2026-04-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0007_remove_cliente_persona_remove_persona_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
