# Generated by Django 6.0 on 2026-06-07 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0008_alter_cliente_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celulares', to='ruta.persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='ruta.cliente'),
        ),
        migrations.AlterField(
            model_name='recojo',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sedes', to='ruta.cliente'),
        ),
    ]
