# Generated by Django 6.0 on 2026-09-21 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0012_documento_archivo_vehiculo_anio_and_more'),
        ('ruta', '0009_alter_celular_persona_alter_persona_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('color', models.CharField(default='#14b8a6', max_length=16)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido')], default='activo', max_length=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='privado', max_length=10),
        ),
        migrations.AddField(
            model_name='recojo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('en_sitio', 'en_sitio'), ('completado', 'completado')], default='pendiente', max_length=12),
        ),
        migrations.AddField(
            model_name='recojo',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='hora_retorno_est',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido_materno',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='recojo',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recojo',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recojo',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recojos', to='ruta.sede'),
        ),
        migrations.AlterField(
            model_name='recojo',
            name='viaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recojos', to='ruta.viaje'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='sedes',
            field=models.ManyToManyField(blank=True, related_name='rutas', to='ruta.sede'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='coordenadas',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sede',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruta.persona'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('programado', 'programado'), ('en curso', 'en curso'), ('completado', 'completado'), ('cancelado', 'cancelado')], default='programado', max_length=15),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='kilometraje_inicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='ruta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='ruta.ruta'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='mantenimiento.vehiculo'),
        ),
        migrations.CreateModel(
            name='ViajeGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('combustible', 'Combustible'), ('peaje', 'Peaje'), ('caja_chica', 'Caja chica')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, default='', max_length=120)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='ruta.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='RecojoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ruta.recojo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ruta.tiporesiduo')),
            ],
            options={
                'unique_together': {('recojo', 'tipo')},
            },
        ),
    ]
