# Generated by Django 6.0 on 2026-09-22 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0014_completar_viajes_recojos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(blank=True, default='', max_length=11)),
                ('razon_social', models.CharField(blank=True, default='', max_length=120)),
                ('nombre_comercial', models.CharField(blank=True, default='', max_length=120)),
                ('direccion', models.CharField(blank=True, default='', max_length=160)),
                ('registro_mtc', models.CharField(blank=True, default='', max_length=40)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('serie_guia', models.CharField(default='T001', max_length=8)),
                ('correlativo', models.PositiveIntegerField(default=0)),
                ('destinatario_documento', models.CharField(blank=True, default='', max_length=11)),
                ('destinatario_razon_social', models.CharField(blank=True, default='', max_length=120)),
                ('punto_llegada', models.CharField(blank=True, default='', max_length=160)),
                ('motivo_traslado', models.CharField(default='Traslado de residuos sólidos', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='GuiaRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=8)),
                ('numero', models.PositiveIntegerField()),
                ('fecha_emision', models.DateField()),
                ('fecha_traslado', models.DateField()),
                ('motivo_traslado', models.CharField(default='Traslado de residuos sólidos', max_length=80)),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('anulada', 'Anulada')], default='emitida', max_length=10)),
                ('emisor_ruc', models.CharField(blank=True, default='', max_length=11)),
                ('emisor_razon_social', models.CharField(blank=True, default='', max_length=120)),
                ('emisor_direccion', models.CharField(blank=True, default='', max_length=160)),
                ('emisor_registro_mtc', models.CharField(blank=True, default='', max_length=40)),
                ('remitente_documento', models.CharField(blank=True, default='', max_length=11)),
                ('remitente_razon_social', models.CharField(blank=True, default='', max_length=120)),
                ('destinatario_documento', models.CharField(blank=True, default='', max_length=11)),
                ('destinatario_razon_social', models.CharField(blank=True, default='', max_length=120)),
                ('punto_partida', models.CharField(blank=True, default='', max_length=160)),
                ('punto_llegada', models.CharField(blank=True, default='', max_length=160)),
                ('vehiculo_placa', models.CharField(blank=True, default='', max_length=50)),
                ('vehiculo_marca', models.CharField(blank=True, default='', max_length=100)),
                ('conductor_nombre', models.CharField(blank=True, default='', max_length=120)),
                ('conductor_documento', models.CharField(blank=True, default='', max_length=15)),
                ('conductor_licencia', models.CharField(blank=True, default='', max_length=20)),
                ('peso_total_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_emitidas', to=settings.AUTH_USER_MODEL)),
                ('recojo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guia', to='ruta.recojo')),
            ],
            options={
                'ordering': ['-fecha_emision', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='GuiaRemisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
                ('unidad', models.CharField(default='KG', max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ruta.guiaremision')),
            ],
        ),
        migrations.AddConstraint(
            model_name='guiaremision',
            constraint=models.UniqueConstraint(fields=('serie', 'numero'), name='unique_guia_serie_numero'),
        ),
    ]
