export const qk = {
  dashboard: (params) => ["dashboard", params],
  clientes: ["clientes"],
  ciudades: ["ciudades"],
  sedes: ["sedes"],
  viajes: ["viajes"],
  vehiculos: ["vehiculos"],
  rutas: ["rutas"],
  recojos: ["recojos"],
  usuarios: ["usuarios"],
  personal: ["personal"],
  roles: ["roles"],
  rolesCatalogo: ["roles", "catalogo"],
  categoriasGasto: ["categorias-gasto"],
  fallas: ["fallas"],
  mantenimientos: ["mantenimientos"],
  documentos: (params) => ["documentos", params],
  tiposFalla: ["tipos-falla"],
  tiposServicio: ["tipos-servicio"],
  servicios: ["servicios-vehiculo"],
  notificaciones: ["notificaciones"],
  emisor: ["emisor"],
};
