# Generated by Django 5.2.8 on 2025-11-20 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entidad', models.CharField(choices=[('user', 'user'), ('vehiculo', 'vehiculo')], default='user', max_length=20)),
                ('entidad_id', models.IntegerField()),
                ('tipo_documento', models.CharField(choices=[('certificacion', 'certificacion'), ('soat', 'soat'), ('licencia', 'licencia'), ('seguro', 'seguro')], default='certificacion', max_length=20)),
                ('numero_documento', models.CharField(max_length=20)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('vencido', 'vencido'), ('inactivo', 'inactivo')], default='activo', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='carga_neta_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('activo', 'activo'), ('mantenimiento', 'mantenimiento'), ('inactivo', 'inactivo')], default='activo', max_length=50),
        ),
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('solucionado', 'solucionado')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('critica', 'critica'), ('alta', 'alta'), ('media', 'media'), ('baja', 'baja')], default='media', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_repostado', models.DateField()),
                ('fecha_solucionado', models.DateField(blank=True, null=True)),
                ('usuario_reporta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('preventivo', 'preventivo'), ('correctivo', 'correctivo')], default='preventivo', max_length=20)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('proveedor', models.CharField(max_length=50)),
                ('fallas', models.ManyToManyField(to='mantenimiento.falla')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.vehiculo')),
            ],
        ),
    ]
