# Generated by Django 5.2.8 on 2025-11-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_documento_vehiculo_carga_neta_kg_vehiculo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fallas',
            field=models.ManyToManyField(related_name='mantenimientos', to='mantenimiento.falla'),
        ),
    ]
