# Generated by Django 5.2.8 on 2025-11-22 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_alter_mantenimiento_fallas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='falla',
            old_name='fecha_repostado',
            new_name='fecha_reportado',
        ),
    ]
