# Generated by Django 6.0 on 2026-04-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_rename_fecha_repostado_falla_fecha_reportado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje_actual',
            field=models.IntegerField(default=0),
        ),
    ]
