# Generated by Django 6.0 on 2026-06-07 23:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_vehiculo_kilometraje_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falla',
            name='fecha_reportado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='falla',
            name='prioridad',
            field=models.CharField(choices=[('critica', 'critica'), ('alta', 'alta'), ('media', 'media'), ('baja', 'baja')], default='baja', max_length=20),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo_mantenimiento',
            field=models.CharField(choices=[('preventivo', 'preventivo'), ('correctivo', 'correctivo'), ('costo_cero', 'costo_cero')], default='preventivo', max_length=20),
        ),
    ]
