# Generated by Django 6.0 on 2026-06-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0006_alter_falla_fecha_reportado_alter_falla_prioridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
