# Generated by Django 6.0 on 2026-08-07 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0008_alter_mantenimiento_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falla',
            name='fecha_reportado',
            field=models.DateField(default=datetime.date(2026, 8, 7)),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2026, 8, 7)),
        ),
    ]
