# Generated by Django 6.0 on 2026-08-07 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0009_alter_falla_fecha_reportado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falla',
            name='fecha_reportado',
            field=models.DateField(default=datetime.datetime(2026, 8, 7, 3, 33, 3, 651698, tzinfo=datetime.timezone.utc)),
        ),
    ]
