# Generated by Django 6.0 on 2026-08-07 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0010_alter_falla_fecha_reportado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falla',
            name='fecha_reportado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
