# Generated by Django 6.0 on 2026-09-21 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0011_alter_falla_fecha_reportado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='conductor_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='nivel_combustible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='proximo_mantenimiento_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('furgon', 'Furgón'), ('camion', 'Camión'), ('van', 'Van'), ('otro', 'Otro')], default='furgon', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='vin',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='numero_documento',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('certificacion', 'certificacion'), ('soat', 'soat'), ('licencia', 'licencia'), ('seguro', 'seguro'), ('contrato', 'contrato'), ('manifiesto', 'manifiesto'), ('revision_tecnica', 'revision_tecnica')], default='certificacion', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_entidad',
            field=models.CharField(choices=[('user', 'user'), ('vehiculo', 'vehiculo'), ('cliente', 'cliente')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fallas',
            field=models.ManyToManyField(blank=True, related_name='mantenimientos', to='mantenimiento.falla'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='proveedor',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
